### ISSUE TITLE
use of strdup() is causing some warnings

### ISSUE THREAD

**Issue by andy5995** [lib-x/xstr#7]
Linux distro is Debian 9. gcc version is gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516

These are the warnings I get when I compile (I found some [info about it here](http://computer-programming-forum.com/47-c-language/ba606293785fb07a.htm)). I got the same messages before switching the build system, btw.

../../src/str.c:200:8: warning: implicit declaration of function ‘strdup’ [-Wimplicit-function-declaration]
  tmp = strdup(*dest);
        ^~~~~~
../../src/str.c:200:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp = strdup(*dest);
      ^
../../src/str.c:206:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp1 = strdup(tmp + index);
       ^
../../src/str.c: In function ‘xstr_insert_c_n’:
../../src/str.c:243:6: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp = strdup(*dest);
      ^
../../src/str.c:249:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp1 = strdup(tmp + index);
       ^
../../src/str.c: In function ‘xstr_delete’:
../../src/str.c:293:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp1 = strdup(*dest);
       ^
../../src/str.c:299:7: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
  tmp2 = strdup(*(dest) + end + 1);

**Comment by the-sushi** [comment]
This should fix it: https://github.com/lib-x/xstr/commit/22147d302595d741a19a9685e471249bf34f8934

**Comment by andy5995** [comment]
Not fixed for me. I have strdup()

I experimented some and 2 ways I was able to eliminate the warning was:

    CFLAGS=-D _GNU_SOURCE ../configure

or by changing the std flag to -std=gnu90.

https://stackoverflow.com/questions/9427145/how-do-i-remove-the-following-implicit-declaration-of-function-warnings

**Comment by the-sushi** [comment]
Try it now: https://github.com/lib-x/xstr/commit/be4cd5a1bdb0a694502e870b5c42b5a835abaddc

**Comment by andy5995** [comment]
works for me.
